const ENCYCLOPEDIA_TO_TOSSUP: Record<string, string> = {
  "ls-photosynthesis": "bio-energy",
  "ls-cellular-respiration": "bio-energy",
  "ls-reg-resp-photosyn": "bio-energy",
  "ls-cell-organelles": "bio-cells",
  "ls-cell-processes": "bio-cells",
  "ls-cell-division": "bio-cells",
  "ls-dna-rna": "bio-genetics",
  "ls-genetics": "bio-inheritance",
  "ls-mutations": "bio-genetics",
  "ls-reg-genetics": "bio-genetics",
  "ls-evolution": "bio-evolution",
  "ls-classification": "bio-evolution",
  "ls-reg-phyla": "bio-evolution",
  "ls-ecology": "bio-ecology",
  "ls-biomes": "bio-ecology",
  "ls-population-ecology": "bio-ecology",
  "ls-symbiosis": "bio-ecology",
  "ls-biodiversity": "bio-ecology",
  "ls-bacteria-viruses": "bio-microbes",
  "ls-immune": "bio-microbes",
  "ls-fungi-protists": "bio-microbes",
  "ls-plant-biology": "bio-cells",
  "ls-circulatory": "bio-body-systems",
  "ls-respiratory": "bio-body-systems",
  "ls-digestive": "bio-body-systems",
  "ls-nervous": "bio-body-systems",
  "ls-endocrine": "bio-body-systems",
  "ls-skeletal-muscular": "bio-body-systems",
  "ls-reproductive": "bio-body-systems",
  "ls-reg-anatomy": "bio-body-systems",
  "ps-motion": "phys-motion",
  "ps-reg-kinematics": "phys-motion",
  "ps-newtons-laws": "phys-forces",
  "ps-forces": "phys-forces",
  "ps-reg-forces": "phys-forces",
  "ps-momentum": "phys-forces",
  "ps-simple-machines": "phys-forces",
  "ps-work-energy-power": "phys-energy",
  "ps-kinetic-potential": "phys-energy",
  "ps-thermodynamics": "phys-energy",
  "en-forms": "phys-energy",
  "en-conservation": "phys-energy",
  "ps-waves": "phys-waves",
  "ps-sound": "phys-waves",
  "ps-light": "phys-waves",
  "ps-reflection-refraction": "phys-waves",
  "ps-optics": "phys-waves",
  "ps-reg-waves": "phys-waves",
  "ps-electricity": "phys-electricity",
  "ps-circuits": "phys-electricity",
  "ps-magnetism": "phys-magnetism",
  "ps-states-of-matter": "chem-states-of-matter",
  "ch-atomic-structure": "chem-atoms-periodic-table",
  "ch-periodic-table": "chem-atoms-periodic-table",
  "ch-elements-compounds": "chem-atoms-periodic-table",
  "ch-reg-nomenclature": "chem-atoms-periodic-table",
  "ch-reg-trends": "chem-atoms-periodic-table",
  "ch-chemical-bonds": "chem-bonding",
  "ch-chemical-reactions": "chem-reactions",
  "ch-reaction-types": "chem-reactions",
  "ch-redox": "chem-reactions",
  "ch-organic": "chem-reactions",
  "hewitt-ch17": "chem-atoms-periodic-table",
  "ch-acids-bases": "chem-solutions-acids",
  "ch-solutions": "chem-solutions-acids",
  "ch-reg-acids": "chem-solutions-acids",
  "ch-mole": "chem-stoichiometry",
  "ch-reg-gas-laws": "chem-stoichiometry",
  "ch-states-matter": "chem-states-of-matter",
  "math-pemdas": "math-number-sense",
  "math-number-theory": "math-number-sense",
  "math-fractions": "math-fractions-percent",
  "math-ratios": "math-ratios-proportions",
  "math-exponents": "math-exponents-sci-notation",
  "math-roots": "math-radicals",
  "math-algebra-expressions": "math-linear-equations",
  "math-linear-eq": "math-linear-equations",
  "math-systems": "math-linear-equations",
  "math-word-problems": "math-linear-equations",
  "math-functions": "math-graphs-slope",
  "math-coordinate": "math-graphs-slope",
  "math-data-graphs": "math-graphs-slope",
  "math-probability": "math-probability-stats",
  "math-statistics": "math-probability-stats",
};

const SUBJECT_TO_PRACTICE: Record<string, string> = {
  "Life Science": "biology",
  biology: "biology",
  "Physical Science": "physics",
  physics: "physics",
  Chemistry: "chemistry",
  chemistry: "chemistry",
  "Earth & Space Science": "earth",
  Energy: "physics",
  Math: "math",
  math: "math",
};

export function tossupTopicForEncyclopedia(topicId: string) {
  return ENCYCLOPEDIA_TO_TOSSUP[topicId];
}

export function practiceSubjectFor(label: string) {
  return SUBJECT_TO_PRACTICE[label] ?? label.toLowerCase();
}
